# Air Quality

In [35]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#load data
data = pd.read_excel('AirQualityUCI.xlsx')

data.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,2004-03-10,18:00:00,2.6,1360.00,150,11.881723,1045.50,166.0,1056.25,113.0,1692.00,1267.50,13.60,48.875001,0.757754
1,2004-03-10,19:00:00,2.0,1292.25,112,9.397165,954.75,103.0,1173.75,92.0,1558.75,972.25,13.30,47.700000,0.725487
2,2004-03-10,20:00:00,2.2,1402.00,88,8.997817,939.25,131.0,1140.00,114.0,1554.50,1074.00,11.90,53.975000,0.750239
3,2004-03-10,21:00:00,2.2,1375.50,80,9.228796,948.25,172.0,1092.00,122.0,1583.75,1203.25,11.00,60.000000,0.786713
4,2004-03-10,22:00:00,1.6,1272.25,51,6.518224,835.50,131.0,1205.00,116.0,1490.00,1110.00,11.15,59.575001,0.788794

In [11]:
#checking duplicate values
print("Number of duplicate values: ", data.duplicated().sum())
print('\n')

#checking the data types of the columns
data.info()
print('\n')

#checking for null values
data.isnull().sum()
print('\n')

#dropping unnecessary features
data1 = data.drop(['Date','Time'], axis=1)

data1.head()
data1.describe()

Number of duplicate values:  0


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9357 entries, 0 to 9356
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           9357 non-null   datetime64[ns]
 1   Time           9357 non-null   object
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   float64
 4   NMHC(GT)       9357 non-null   int64
 5   C6H6(GT)       9357 non-null   float64
 6   PT08.S2(NMHC)  9357 non-null   float64
 7   NOx(GT)        9357 non-null   float64
 8   PT08.S3(NOx)   9357 non-null   float64
 9   NO2(GT)        9357 non-null   float64
 10  PT08.S4(NO2)   9357 non-null   float64
 11  PT08.S5(O3)    9357 non-null   float64
 12  T              9357 non-null   float64
 13  RH             9357 non-null   float64
 14  AH             9357 non-null   float64
dtypes: datetime64[ns](1), float64(12), int64(1), object(1)
memory usage: 1.1+ MB

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
count,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000
mean,-34.207524,1048.869652,-159.090093,1.865576,894.475963,168.604200,794.872333,58.135898,1391.363266,974.951534,9.776600,39.483611,-6.837604
std,77.657170,329.817015,139.789093,41.380154,342.315902,257.424561,321.977031,126.931428,467.192382,456.922728,43.203438,51.215645,38.976670
min,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000
25%,0.600000,921.000000,-200.000000,4.004958,711.000000,50.000000,637.000000,53.000000,1184.750000,699.750000,10.950000,34.050000,0.692275
50%,1.500000,1052.500000,-200.000000,7.886653,894.500000,141.000000,794.250000,96.000000,1445.500000,942.000000,17.200000,48.550000,0.976823
75%,2.600000,1221.250000,-200.000000,13.636091,1104.750000,284.200000,960.250000,133.000000,1662.000000,1255.250000,24.075000,61.875000,1.296223
max,11.900000,2039.750000,1189.000000,63.741476,2214.000000,1479.000000,2682.750000,339.700000,2775.000000,2522.750000,44.600000,88.725000,2.231036

In [12]:
#handling missing values
def handle_missing_value(df, column_name, replace_value):
  # Check if the column exists
  if column_name not in df.columns:
    raise ValueError(f"Column '{column_name}' does not exist in the DataFrame.")
  # Calculation for replacing values
  filtered_data = df[df[column_name] != replace_value]
  column_mean = filtered_data[column_name].mean()
  df.loc[df[column_name] == replace_value, column_name] = column_mean
  return df

In [13]:
#handling missing values of each column
df = handle_missing_value(data1, 'CO(GT)', -200)
df = handle_missing_value(data1, 'PT08.S1(CO)', -200)
df = handle_missing_value(data1, 'NMHC(GT)', -200)
df = handle_missing_value(data1, 'C6H6(GT)', -200)
df = handle_missing_value(data1, 'PT08.S2(NMHC)', -200)
df = handle_missing_value(data1, 'NOx(GT)', -200)
df = handle_missing_value(data1, 'PT08.S3(NOx)', -200)
df = handle_missing_value(data1, 'NO2(GT)', -200)
df = handle_missing_value(data1, 'PT08.S4(NO2)', -200)
df = handle_missing_value(data1, 'PT08.S5(O3)', -200)
df = handle_missing_value(data1, 'T', -200)
df = handle_missing_value(data1, 'RH', -200)
df = handle_missing_value(data1, 'AH', -200)
df.describe()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
count,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000
mean,2.152750,1099.707856,218.811816,10.082993,939.029205,246.881252,835.370973,113.075515,1456.143486,1022.780725,18.316054,49.232360,1.025530
std,1.316068,212.796116,63.870229,7.302474,261.557856,193.419417,251.741784,43.911095,339.365351,390.609000,8.658396,16.974308,0.395836
min,0.100000,647.250000,7.000000,0.149048,383.250000,2.000000,322.000000,2.000000,551.000000,221.000000,-1.900000,9.175000,0.184679
25%,1.200000,941.250000,218.811816,4.591495,742.500000,112.000000,665.500000,85.900000,1241.500000,741.750000,12.025000,36.550000,0.746115
50%,2.152750,1074.500000,218.811816,8.593367,923.250000,229.000000,817.500000,113.075515,1456.143486,982.500000,18.275000,49.232360,1.015441
75%,2.600000,1221.250000,218.811816,13.636091,1104.750000,284.200000,960.250000,133.000000,1662.000000,1255.250000,24.075000,61.875000,1.296223
max,11.900000,2039.750000,1189.000000,63.741476,2214.000000,1479.000000,2682.750000,339.700000,2775.000000,2522.750000,44.600000,88.725000,2.231036

In [31]:
#separating independent and dependent variables
X = df.drop(['T','RH','AH'], axis=1)
y = df["RH"]

X_train = X.iloc[:7017]
y_train = y.iloc[:7017]
X_test = X.iloc[7017:]
y_test = y.iloc[7017:]

print(X_train.shape)
print(y_test)

(7017, 10)
7017    70.075001
7018    69.374998
7019    62.474999
7020    64.750001
7021    73.075001
          ...
9352    29.250000
9353    23.725000
9354    18.350000
9355    13.550000
9356    13.125000
Name: RH, Length: 2340, dtype: float64

## Scaling

In [28]:
def minmax(n, original, min, max):
  scaled = 0
  for i in range(n):
    scaled[i] = (original[i] - min) / (max - min)

  return scaled

In [30]:
X_train_scaled = minmax(X_train.shape[0], X_train.values.reshape(-1,1), X_train.min(), X_train.max())

print(X_train_scaled)

TypeError: 'int' object does not support item assignment

## Multivariable Linear Regression with Gradient Descent Algorithm

In [60]:
def gda(X, y, alpha, epoch):
  m = X.shape[0]
  ones = np.ones((m,1))
  X = np.concatenate((ones, X), axis=1)
  n = X.shape[1]
  Theta = np.ones(n)
  h = np.dot(X, Theta)

  cost = np.ones(epoch)
  for i in range (0, epoch):
    Theta[0] = Theta[0] - ((alpha/X.shape[0]) * sum(h-y))
    for j in range (1, n):
      Theta[j] = Theta[j] - ((alpha/X.shape[0]) * sum((h-y) * X[:,j]))
    h = np.dot(X, Theta)
    cost[i] = 1/(2*m) * sum(np.square(h-y))
  return cost, Theta

In [61]:
cost_train, Theta_train = gda(X_train, y_train, 0.0001, 100)
cost_test, Theta_test = gda(X_test, y_test, 0.0001, 100)

print(cost_train)
print(cost_test)

[8.09221084e+012 3.53328752e+018 1.54273303e+024 6.73600772e+029
 2.94113104e+035 1.28418080e+041 5.60709573e+046 2.44821621e+052
 1.06896028e+058 4.66738220e+063 2.03791077e+069 8.89809344e+074
 3.88515867e+080 1.69636990e+086 7.40682965e+091 3.23403082e+097
 1.41206911e+103 6.16549218e+108 2.69202785e+114 1.17541532e+120
 5.13219496e+125 2.24086113e+131 9.78423200e+136 4.27207177e+142
 1.86530708e+148 8.14445703e+153 3.55609975e+159 1.55269349e+165
 6.77949791e+170 2.96012008e+176 1.29247195e+182 5.64329724e+187
 2.46402281e+193 1.07586189e+199 4.69751656e+204 2.05106828e+210
 8.95554286e+215 3.91024271e+221 1.70732230e+227 7.45465091e+232
 3.25491093e+238 1.42118596e+244 6.20529890e+249 2.70940859e+255
 1.18300424e+261 5.16533033e+266 2.25532897e+272 9.84740266e+277
 4.29965386e+283 1.87735020e+289 8.19704070e+294 3.57905926e+300
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf]
[4.67379456e+012 1.35006461e+018 3.89977484e+023 1.12648267e+029
 3.25393966e+034 9.39927760e+039 2.71506016e+045 7.84267897e+050
 2.26542359e+056 6.54386604e+061 1.89025059e+067 5.46014734e+072
 1.57720935e+078 4.55590149e+083 1.31601035e+089 3.80140627e+094
 1.09806808e+100 3.17186174e+105 9.16218865e+110 2.64657503e+116
 7.64485393e+121 2.20828017e+127 6.37880247e+132 1.84257059e+138
 5.32241968e+143 1.53742556e+149 4.44098267e+154 1.28281509e+160
 3.70551896e+165 1.07037023e+171 3.09185417e+176 8.93108007e+181
 2.57981738e+187 7.45201886e+192 2.15257814e+198 6.21790249e+203
 1.79609328e+209 5.18816607e+214 1.49864528e+220 4.32896258e+225
 1.25045715e+231 3.61205033e+236 1.04337103e+242 3.01386473e+247
 8.70580102e+252 2.51474364e+258 7.26404789e+263 2.09828115e+269
 6.06106108e+274 1.75078832e+280 5.05729890e+285 1.46084320e+291
 4.21976810e+296 1.21891541e+302             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf
             inf             inf             inf             inf]

# MSE

In [50]:
def mse(n, y, y1):
  se = 0
  for i in range(n):
    se1 = (y[i] - y1[i])**2
    se += se1

  mse = se/n
  return mse

In [54]:
mse_value = mse(20, cost_train, cost_test)

print("The MSE is: ", mse_value)

The MSE is:  6.904895411652929e+238